sudo: required
services:
    - docker

before_install:
    - docker build -t leamedhurst/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true leamedhurst/react-test npm test

after_success:
    - docker build -t leamedhurst/multi-client ./client
    - docker build -t leamedhurst/multi-ngnix ./nginx
    - docker build -t leamedhurst/multi-server ./server
    - docker build -t leamedhurst/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "@DOCKER_ID" --password-stdin
    - docker push leamedhurst/multi-client
    - docker push leamedhurst/multi-nginx
    - docker push leamedhurst/multi-server
    - docker push leamedhurst/multi-worker



