sudo: required
services:
    - docker

before_install:
    - docker build -t leamedhurst/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true leamedhurst/react-test npm test

after_success:
    - docker build -t leamedhurst/multi-client ./client
    - docker build -t leamedhurst/multi-nginx ./nginx
    - docker build -t leamedhurst/multi-server ./server
    - docker build -t leamedhurst/multi-worker ./worker
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
   
    - docker push leamedhurst/multi-client
    - docker push leamedhurst/multi-nginx
    - docker push leamedhurst/multi-server
    - docker push leamedhurst/multi-worker



