sudo: required
services:
    - docker

before_install:
    - docker build -t leamedhurst/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true leamedhurst/react-test npm test

after_success:
    - docker build -t leamedhurst/multi-client ./client
    - docker build -t leamedhurst/multi-nginx ./nginx
    - docker build -t leamedhurst/multi-server ./server
    - docker build -t leamedhurst/multi-worker ./worker
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
   
    - docker push leamedhurst/multi-client
    - docker push leamedhurst/multi-nginx
    - docker push leamedhurst/multi-server
    - docker push leamedhurst/multi-worker

    #deploy section
deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker2'
    env: 'MultiDocker2-env'
    bucket_name: 'elasticbeanstalk-us-east-1-291085658953'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

